sudo: false
dist: xenial
os:
- linux
- osx
osx_image:
- xcode10.2
language: python
python:
- '3.7'
- '3.6'
- '3.5'
- '3.4'
- '2.7'
- 'pypy3.5-6.0'
- 'pypy2.7-6.0'
install:
  |
  pip install --upgrade pip setuptools tox-travis
script: tox
